# Generated by Django 5.1.1 on 2024-10-08 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodels', '0003_team_alter_player_id_alter_shot_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='dbmodels.player'),
        ),
    ]
